---
title: Managing Applications on Single-Node OpenShift at the Edge
description: >-
  A workshop exploring the creation and management of Single-Node OpenShift clusters,
  and deploying applications to groups of them all at once.
url: labguide.rhte.edgelab.dev
baseurl: /
repository: redhat-na-ssa/rhte-edge-lab-sno
author: James Harmison
theme: jekyll-theme-dinky
encoding: UTF-8
