FROM registry.access.redhat.com/ubi9/nginx-120:latest

COPY nginx.conf /etc/nginx/nginx.conf
COPY conf.d /opt/app-root/etc/nginx.d
COPY server.crt /etc/pki/nginx/server.crt
COPY server.key /etc/pki/nginx/private/server.key
COPY index.html /opt/app-root/src/

EXPOSE 443
USER 0

ENTRYPOINT ["/bin/bash"]
CMD ["-c", "chown -R nginx:nginx /var/lib/nginx && exec /usr/sbin/nginx -g 'daemon off;'"]
