FROM registry.access.redhat.com/ubi9/nginx-120:latest

USER 0
RUN dnf -y install httpd-tools \
 && dnf clean all

COPY nginx.conf /etc/nginx/nginx.conf
COPY entrypoint.sh /usr/local/bin/entrypoint.sh
COPY conf.d /opt/app-root/etc/nginx.d
COPY server.crt /etc/pki/nginx/server.crt
COPY server.key /etc/pki/nginx/private/server.key

ENV USERNAME=""
ENV PASSWORD=""
EXPOSE 443

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
