---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: rust-hello-world
spec:
  lookupPolicy:
    local: true
  tags:
  - importPolicy:
      scheduled: true
    name: 0.1.3
    from:
      kind: DockerImage
      name: quay.io/redhatgov/rust-hello-world:0.1.3
