---
virt_sno_clusters_yaml: |-
  {% for num in range(1, virt_cluster_count + 1) %}
  - name: vm{{ num }}
    ip: '192.168.122.{{ 200 + num }}'
    num: {{ num }}
  {% endfor %}
metal_sno_clusters_yaml: |-
  {% for num in range(1, metal_cluster_count + 1) %}
  - name: metal{{ num }}
    ip: '192.168.99.{{ 200 + num }}'
    num: {{ num }}
  {% endfor %}
sno_clusters_yaml: |
  {{ virt_sno_clusters_yaml -}}
  {{ metal_sno_clusters_yaml -}}
