---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  annotations:
    apps.open-cluster-management.io/reconcile-rate: medium
  name: rust-hello-world
spec:
  type: Git
  pathname: 'https://github.com/redhat-na-ssa/rhte-edge-lab-sno.git'
