---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: rhte-sno
  name: rhte-sno-registry
spec:
  ports:
  - name: registry
    port: 5000
    targetPort: 5000
  selector:
    app: rhte-sno
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: rhte-sno
  name: rhte-sno-image
spec:
  ports:
  - name: image
    port: 8080
    targetPort: 8080
  selector:
    app: rhte-sno
---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    io.podman.annotations.autoremove/rhte-sno: "FALSE"
    io.podman.annotations.init/rhte-sno: "FALSE"
    io.podman.annotations.privileged/rhte-sno: "FALSE"
    io.podman.annotations.publish-all/rhte-sno: "FALSE"
  labels:
    app: rhte-sno
  name: rhte-sno
spec:
  containers:
  - name: registry
    image: docker.io/library/registry:2
    args:
    - /etc/docker/registry/config.yml
    ports:
    - containerPort: 5000
    volumeMounts:
    - mountPath: /var/lib/registry
      name: registry-data
  - name: image
    image: registry.access.redhat.com/ubi9/nginx-120:latest
    command:
    - /bin/bash
    args:
    - -c
    - |-
      set -ex
      cd /opt/app-root/src
      download_source=https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/pre-release/latest-4.12
      download() {
        grep -F "$1" sha256sum.txt | sha256sum -c || curl -LO "$download_source/$1"
      }
      curl -LO "$download_source/sha256sum.txt"
      download rhcos-live.x86_64.iso
      exec nginx -g "daemon off;"
    ports:
    - containerPort: 8080
    volumeMounts:
    - mountPath: /opt/app-root/src
      name: image-data
  volumes:
  - name: registry-data
    persistentVolumeClaim:
      claimName: rhte-sno-registry-data
  - name: image-data
    persistentVolumeClaim:
      claimName: rhte-sno-image-data
