# frozen_string_literal: true
source "https://rubygems.org"

gem "webrick", "~> 1.7"
gem "github-pages", group: :jekyll_plugins

group :jekyll_plugins do
  gem 'jekyll-seo-tag'
  gem 'jekyll-sitemap'
  gem 'jekyll-feed'
  gem 'jekyll-toc'
end
